version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:60UcqGwrIbdTQiNP/uqsN+bnau/wffW4MWGeLgW+H7Y soyangelica.aguilar@gmail.com"
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
