import {
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiCss3,
  SiDjango,
  SiDocker,
  SiFigma,
  SiGit,
  SiGithub,
  SiHeroku,
  SiHtml5,
  SiPhp,
  SiPostman,
  SiPython,
  SiShopify,
  SiVercel,
  SiVite,
  SiWebpack,
  SiWordpress,
  SiWebflow,
} from "react-icons/si";

export const Skills = [
  { title: "Html 5", icon: <SiHtml5 title="HTML5" /> },
  { title: "Css 3", icon: <SiCss3 title="CSS 3" /> },
  { title: "Php", icon: <SiPhp title="PHP" /> },
  { title: "Python", icon: <SiPython title="Python" /> },
  { title: "Django", icon: <SiDjango title="Django" /> },
  { title: "Wordpress", icon: <SiWordpress title="Wordpress" /> },
  { title: "Shopify", icon: <SiShopify title="Shopify" /> },
  { title: "webflow", icon: <SiWebflow title="webflow" /> },
  { title: "Git", icon: <SiGit title="Git" /> },
  { title: "Github", icon: <SiGithub title="Github" /> },
  { tile: "Vite", icon: <SiVite title="Vite" /> },
  { title: "Webpack", icon: <SiWebpack title="Webpack" /> },
  { title: "Vercel", icon: <SiVercel title="Vercel" /> },
  { title: "Heroku", icon: <SiHeroku title="Heroku" /> },
  { title: "Postman", icon: <SiPostman title="Postman" /> },
  { title: "Docker", icon: <SiDocker title="Docker" /> },
  { title: "Figma", icon: <SiFigma title="Figma" /> },
  { title: "Photoshop", icon: <SiAdobephotoshop title="Photoshop" /> },
  { title: "Illustrator", icon: <SiAdobeillustrator title="Illustrator" /> },
];
